### ISSUE TITLE
پیشنهاد برای افزودن یک مورد به فایروال

### ISSUE THREAD

**Issue by sallar75** [mrkiller90/security-#1]
سلام و تشکر بابت وقتی که گذاشتین و اسکریپت خوبی که نوشتین
با توجه به اینکه هنگام فعالسازی SSL برای پنل، یک عدد به پورت اضافه می شود. مثلا پورت لاگین به پنل ۲۰۵۲ بوده، وقتی SSL فعال می شود پورت لاگین به پنل ۲۰۵۳ می شود، لطفا در هنگام افزودن پورت به فایروال، این مورد نیز در نظر گرفته شود که اگر پورت ۲۰۵۲ وارد شد، پورت ۲۰۵۲ و ۲۰۵۳ هر دو در فایروال باز شوند. در حال حاضر به صورت دستی این پورت را باز میکنم.
همچنین پس از اتمام نصب و مراحل اسکریپت، هیچ چیز نمایش داده نمیشود و انگار اسکریپت در حالت اجرا می رود.
خب باید چکار کرد در این موقع؟ با Ctrl + C خارج شد یا اینکه تب SSH را بست و تب SSH جدیدی باز کرد؟
لطفا یک دستور العمل و توضیحات ابتدایی و ساده نیز در نظر بگیرید.

با تشکر

**Comment by mrkiller90** [comment]
حله ، مرسی که اطلاع دادی ، تب رو ببند کنترل سی نزن
